export { render } from "./render"
export { router } from "./route"
export { goTo } from "./goTo"
export { get, post, put, patch , DELETE } from "./Api"
export { back } from "./back"
export { UserObj, PromotionObj } from "./instantiate"
export { download } from "./download"
export {$$} from "./querySelector"
